artifact_location: file:///home/adduser/projects/Mlops-platzi/tracking/experiments_ml/506952113496395628
creation_time: 1768393377798
experiment_id: '506952113496395628'
last_update_time: 1768393377798
lifecycle_stage: active
name: iris_experiment_ml_local
